### ISSUE TITLE
fwrite() expects parameter 2 to be string, object given

### ISSUE THREAD

**Issue by itsazzad** [hellosign/hellosign-php-sdk#13]
I was following : https://www.hellosign.com/api/signature_request/files  

```
$client = new HelloSign\Client('SIGN_IN_AND_CONFIRM_EMAIL_TO_SEE_YOUR_API_KEY_HERE');
$client->getFiles('fa5c8a0b0f492d768749333ad6fcc214c111e967', $dest_file_path, HelloSign\SignatureRequest::FILE_TYPE_PDF);
```

but getting error:

```
exception 'ErrorException' with message 'fwrite() expects parameter 2 to be string, object given' in hellosign/hellosign-php-sdk/library/HelloSign/Client.php:228
Stack trace:
#1 /vendor/hellosign/hellosign-php-sdk/library/HelloSign/Client.php(228): fwrite(Resource id #3, Object(stdClass))
#2 HelloSign\Client->getFiles('515ffc0b46664ea...', '/...', 'pdf')
```

**Comment by renderf0x** [comment]
Hi @itsazzad -

How closely do your parameters match what you've provided in the stack trace #2 section above?, in particular I'm curious if perhaps you're passing a filename in your destination path -- you'll need to provide this.

Also, are you instantiating your client with a HelloSign API Key?

**Comment by itsazzad** [comment]
@renderf0x I am using proper `API KEY`, proper `signature_id`, `dest_file_path` like as `/var/ww/html/uploads/signed_doc.pdf` 
But seems to be that the rest api request is not returning string but returning Object.

**Comment by itsazzad** [comment]
@renderf0x Any news?

**Comment by renderf0x** [comment]
Heya @itsazzad -- I see what you're running into here.

In addition to what you sent over, I'd guess you're also seeing this error:
`PHP Fatal error:  Uncaught HelloSign\Error: [not_found] Not ready`

This API endpoint has been changed so that if the files are not yet ready to be downloaded, we'll return an error such as this (as otherwise you can see incomplete results in cases of multiple signers).

I'd guess that if you take the Signature Request ID you're getting, and try this same getFiles request again a small bit later, that this would succeed (as the files would be ready then).

We should adjust the SDK to account for this by checking for the error here before attempting to write the file, but we'll still be returning this Not ready error up the chain.

You should be able to catch this, though, and have your application retry in the event of a not found error.
We'll take a look at passing the error better in the SDK, but a try/catch with a timed retry here should take care of this for you for now.

Cheers,

//Derek

**Comment by BHSPitMonkey** [comment]
Hi @itsazzad,

I checked our logs and it seems you're passing a `signature_id` instead of a `signature_request_id`, which is invalid. A single signature request can have multiple signature objects associated with it; This API endpoint expects the ID of the signature request itself.

Thanks,
Stephen

**Comment by renderf0x** [comment]
@itsazzad , @BHSPitMonkey probably has the answer you're looking for here -- please try his suggestion.

In the meantime, I've fixed error handling on that function as well.

**Comment by itsazzad** [comment]
@BHSPitMonkey and @renderf0x ,
Its working but unfortunately not getting the signature in the document even after firing the queue after `one minute` of the `signature_request_signed` event.

I was sending `related_signature_id`; 
Now I am using `$request_data['event']['event_metadata']['related_signature_id']` to track the `related_signature_id` and `$request_data['signature_request']['signature_request_id']` to get the files.

```
if($request_data['event']['event_type']=='signature_request_signed'){
   //Matching $request_data['event']['event_metadata']['related_signature_id']

   //Now in a queue trying to get files
    $client->getFiles($request_data['signature_request']['signature_request_id'], $dest_file_path, HelloSign\SignatureRequest::FILE_TYPE_PDF);
}
```

![screen shot 2015-09-02 at 8 15 25 pm](https://cloud.githubusercontent.com/assets/54909/9633591/6f2caa72-51af-11e5-8b14-e8f148ece9c6.png)

**Comment by itsazzad** [comment]
## Trying with `signature_request_all_signed` event.

Yes its working with  `signature_request_all_signed`.
Thanks,

**Comment by BHSPitMonkey** [comment]
Yes, waiting for the "all signed" event will allow you to grab the final
signed PDF. Note that if you call getFiles too close to the time the event
fires, you may get an error indicating the files are not yet ready. Ideally
your code will be able to handle this and try again.
