### ISSUE TITLE
`Client#getFiles` method should accept `get_url` parameter

### ISSUE THREAD

**Issue by garnold** [hellosign/hellosign-php-sdk#24]
From the API reference:

> get_url optional Boolean. If true, the response will contain a url link to the file instead. Links are only available for PDFs and have a TTL of 3 days. (default = false)

**Comment by garnold** [comment]
Note: looks like we can use `SignatureRequest#files_url` as a workaround.

**Comment by rmelencio** [comment]
Hi @garnold ,

Thanks for your suggestion.  This will go into our queue of items.  Although glad to hear you have a workaround for the meantime.

-Ronald

**Comment by BHSPitMonkey** [comment]
@garnold - For clarification:
- The URL in `SignatureRequest#files_url` is to be accessed through an API call, and requires an API key to be accessed. This is most suitable for your backend to use to fetch the actual PDF or ZIP. This can already be accessed by using `Client#getFiles` in the PHP SDK.
- The URL returned by `/signature_request/files/[ID]?get_url=1` is a special pre-authenticated (and temporary) URL, which is most suitable for client-side use (i.e. to display in an HTML page or to expose a Download link to your user without needing to act as a proxy). Proper support for this in the PHP SDK will be landing very soon.

**Comment by garnold** [comment]
@BHSPitMonkey Thanks for the clarification!  Curious, how long is the temporary URL valid?

**Comment by BHSPitMonkey** [comment]
@garnold - Three days, and the returned object contains both the URL string and a unix timestamp indicating when the link will expire.

Since it's valid for 3 days, you may not wish to use this link in scenarios such as emails to users. Instead, consider creating a URL in your application which calls this API on the backend and redirects the request to the returned URL, or which fetches the full file on your server and serves it to your customer.

**Comment by desmondw** [comment]
Implemented.

**Comment by garnold** [comment]
Awesome, thanks @desmondw !
