### ISSUE TITLE
No recipients specified in run the code

### ISSUE THREAD

**Issue by prasad1205** [hellosign/hellosign-php-sdk#68]
$client = new HelloSign\Client('62ae8b50d5293a72ae0aa31ef0f586d1fcf5c89707b9e68b906dd64864b87cb3');
$request = new HelloSign\TemplateSignatureRequest;
$request->enableTestMode();
$request->setTemplateId('fe9425d1918ee9d099fff6875c34379622b9af96');
$request->setSubject('Purchase Order');
$request->setMessage('Glad we could come to an agreement.');
$request->setSigner('Client', 'venkataprasad.k@tychons.com', 'Prasad');
$request->setCC('Accounting', '09991a1205@gmail.com');
$client_id = '0005fc6cf93ce7ce6116778265107d5a';
$embedded_request = new HelloSign\EmbeddedSignatureRequest($request, $client_id);
$response = $client->createEmbeddedSignatureRequest($embedded_request);
followed above code but not getting any response from api. 
getting errors like Fatal error: Uncaught HelloSign\Error: [bad_request] No recipients specified throw

**Comment by jyoung488** [comment]
@prasad1205 Thanks for sending that over! Please refresh your API key since this is a public repository and you'll want to keep this information private. For more information, please see the [HelloSign Help Center](https://faq.hellosign.com/hc/en-us/articles/236400127-Where-do-I-find-my-API-Key-).

When using a Template to send a signature request, you'll want to use the signer roles you specified when creating the Template on HelloSign.com. For example, the Template would need the "Client" role defined in order to set the signer.
For more information on creating a template, please see this [article](https://faq.hellosign.com/hc/en-us/articles/211241477-How-do-I-create-a-template-).

Please write into apisupport@hellosign.com if you have any other technical questions about the API. Thank you!
