### ISSUE TITLE
Add ability to enable test mode for embedded template URL endpoint

### ISSUE THREAD

**Issue by jyoung488** [hellosign/hellosign-php-sdk#73]
Need to be able to set enableTestMode() when retrieving the edit_url for embedded templates

**Comment by latoyazamill** [comment]
Customer Feedback: "Based on my digging through the PHP SDK, the issue comes from the fact that you can't retrieve templates in test mode after you've saved a draft. This is all doable from Guzzle/Curl so I'm going to be implementing our system with that, but it may be of use for your developers to know that."

**Comment by jyoung488** [comment]
Resolved in #75
